### ISSUE TITLE
Review of 2.4.0 release

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/glaze#1]
**NOTE**: the items in this check list should only be checked off by the person doing the review. The author of the package may indicate the completion of any outstanding items in comments.

- [x] Repository in the [build2-packaging organization][build2-packaging] if third-party package.
- [x] Repository/project/package names consistent with upstream, [Debian][debian-pkgs] (see [repository name][rep-name], [package name][pkg-name]).
- [x] If library without `lib` prefix, no clashes with executable named (see [package name][pkg-name]).
- [x] Uses git submodule and symlinks for upstream, submodule at correct release commit (see [upstream submodule][upstream-submodule], [upstream symlinks][upstream-symlink]).
- [x] Follows upstream layout (within reason) (see [package layout][upstream-layout]).
- [x] [Does not bundle dependencies][dont-bundle-deps].

- [x] Successful builds on [queue.cppget.org][queue].
- [x] Package archive sizes are not excessive and don't contain unnecessary files.

- [x] `manifest`: `name`/`project`/`version` values make sense.
- [x] `manifest`: [`summary`][manifest-summary] value follows guidelines.
- [x] `manifest`: [`license`][manifest-license] value is SPDX, matches upstream license(s).
- [x] `manifest`: [`depends`][manifest-depends] values make sense, have corresponding [buildfile imports][manifest-depends-import].

- [x] `build/bootstrap.build`: makes sense (project name, modules; see [project-wide build system files][build-wide]).
- [x] `build/root.build`:      makes sense (`cxx.std=latest`).
- [x] `build/export.build`:    makes sense.

- [x] Header/Source `buildfile`: [bdep-new generated][use-bdep-new].
- [x] Header `buildfile`: [overall makes sense][hdr-build].
- [x] Header `buildfile`: headers installed into library subdirectory or include library name ([background][bad-header-inclusion]).
- [x] Source `buildfile`: [overall makes sense][src-build].
- [x] Source `buildfile`: [library is not header-only if upstream supports compiled][header-only].
- [x] Source `buildfile`: [doesn't use or export undesirable options][compile-options].

- [x] Root `buildfile`: [overall makes sense][root-build].
- [x] Root `buildfile`: includes upstream `LICENSE` file (or equivalent).
- [x] Root `buildfile`: [doesn't build main targets][root-main-targets].

- [x] Doesn't violate any other [What Not to Do][not-to-do] points without good reason.

- [x] Above `buildfile` checks applied to tests/examples/etc subprojects/packages.
- [x] If smoke test, [makes sense][test-smoke] (includes public header, calls non-inline function).

- [x] `PACKAGE-README.md`: [makes sense][pkg-readme].

- [x] Above checks applied to all packages.

- [x] Repository `README.md`: [makes sense][rep-readme].

- [x] Release is tagged and pushed to `git` repository.

[build2-packaging]: https://github.com/build2-packaging/
[upstream-layout]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-change-upstream
[debian-pkgs]: https://packages.debian.org/
[rep-name]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-repo-name
[pkg-name]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-package-name
[upstream-submodule]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-repo-submodule
[upstream-symlink]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-fill-source
[upstream-layout]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-change-upstream
[dont-bundle-deps]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-bundle

[queue]: https://queue.cppget.org

[not-to-do]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-do

[manifest-license]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-root-manifest-license
[manifest-summary]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-root-manifest-summary
[manifest-depends]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-fill-depend
[manifest-depends-import]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-adjust-build-src-source-dep

[build-wide]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-adjust-build-wide

[use-bdep-new]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-from-scratch
[compile-options]: https://github.com/build2/HOWTO/blob/master/entries/compile-options-in-buildfile.md
[header-only]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-header-only
[bad-header-inclusion]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#howto-bad-inclusion-practice
[hdr-build]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-adjust-build-src-header
[src-build]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-adjust-build-src-source

[root-build]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-root-buildfile
[root-main-targets]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-main-target-root-buildfile

[test-smoke]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-test-smoke-adjust

[pkg-readme]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-root-package-readme
[rep-readme]: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-repo-readme

**Comment by boris-kolpackov** [comment]
Issues:

* Linking on `-pthread` to header-only library is incorrect: https://github.com/build2/HOWTO/blob/master/entries/make-header-only-library.md

* Links in libgalze/README.md assume other documentation is in docs/, which
  will not be the case once installed. Makes sense to install documentation
  into docs/ subdirectory: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#core-root-buildfile-doc

* In `libglaze-tests/buildfile`:

```
if($cxx.target.class != 'windows')
  exe{lib_test}: cxx.coptions += -ldl
if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols
```

Should probably be (note that there are two mistake in the above fragment):

```
if ($cxx.target.class != 'windows')
  exe{lib_test}: cxx.loptions += -ldl
if ($cxx.target.system == 'mingw32')
  libs{test_lib}: cxx.loptions += -Wl,--export-all-symbols
```

* `libglaze-tests/buildfile` violates https://github.com/build2/HOWTO/blob/master/entries/compile-options-in-buildfile.md

* `summary` in `libglaze-tests/manifest` does not follow guidelines.


Notes:

* There is an (unrelated) executable called `glaze` in Debian: https://packages.debian.org/search?searchon=contents&keywords=glaze&mode=path&suite=unstable&arch=any

**Comment by helmesjo** [comment]
Updated, see latest commits.

**Comment by helmesjo** [comment]
https://ci.stage.build2.org/@ba45bf88-e46c-4ee7-8370-185d41173853

**Comment by boris-kolpackov** [comment]
Migrated to cppget.org, `testing` section. Thank you.
